  version: '3.1'

  services:
    product:
      build: product-service
#      mem_limit: 350m
      environment:
        - SPRING_PROFILES_ACTIVE=docker

    recommendation:
      build: recommendation-service
#      mem_limit: 350m
      environment:
        - SPRING_PROFILES_ACTIVE=docker

    review:
      build: review-service
#      mem_limit: 350m
      environment:
        - SPRING_PROFILES_ACTIVE=docker

    product-composite:
      build: product-composite-service
#      mem_limit: 350m
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=docker